# Generated by Django 4.1.7 on 2023-05-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('p_l', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_buying_power', models.DecimalField(decimal_places=2, max_digits=20)),
                ('option_buying_power', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bought_at', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_l_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p_l_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('W', 'Working'), ('F', 'Filled'), ('C', 'Cancelled')], max_length=1)),
                ('side', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('quantity', models.SmallIntegerField()),
                ('tif', models.CharField(choices=[('IOC', 'ImmediateOrCancelled'), ('GFD', 'GoodForDay'), ('GTC', 'GoodTilCanceled'), ('AON', 'AllOrNone'), ('FOK', 'FillOrKill'), ('OCO', 'OneCancelsOther')], max_length=3)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
    ]
