# Generated by Django 4.1.7 on 2023-06-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeorder',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='position',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='symbol',
        ),
    ]
