# Generated by Django 4.1.7 on 2023-05-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activeorder_id_alter_portfolio_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='p_l',
            new_name='p_L',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
