# Generated by Django 4.1.7 on 2023-06-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_name_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='accountId',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
