# Generated by Django 4.1.7 on 2023-06-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_email_user_accountid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accountId',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
