# Generated by Django 4.1.7 on 2023-06-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_accountid_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.portfolio'),
        ),
    ]
