# Generated by Django 4.1.7 on 2023-06-19 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.portfolio'),
        ),
    ]
