# Generated by Django 4.1.7 on 2023-06-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='p_L',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='value',
        ),
        migrations.RemoveField(
            model_name='position',
            name='p_l_day',
        ),
        migrations.RemoveField(
            model_name='position',
            name='p_l_total',
        ),
    ]
