# Generated by Django 4.1.7 on 2023-06-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_activeorder_expiration_activeorder_num_shares_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeorder',
            name='quantity',
        ),
    ]
