# Generated by Django 4.1.7 on 2023-07-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_activeorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorder',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4),
        ),
    ]
