# Generated by Django 4.1.7 on 2023-07-06 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_activeorder_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorder',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 0, 0)),
        ),
    ]
