# Generated by Django 4.1.7 on 2023-07-09 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_activeorder_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorder',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 0, 0)),
        ),
    ]
