# Generated by Django 4.1.7 on 2023-07-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_activeorder_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeorder',
            name='ask',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
