# Generated by Django 4.1.7 on 2023-07-12 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_activeorder_ask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeorder',
            name='expiration',
        ),
        migrations.AddField(
            model_name='activeorder',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 0, 0)),
        ),
        migrations.AddField(
            model_name='activeorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 0, 0)),
        ),
    ]
