# Generated by Django 4.1.7 on 2023-07-14 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_activeorder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeorder',
            name='activation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activeorder',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 0, 0)),
        ),
        migrations.AlterField(
            model_name='activeorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 0, 0)),
        ),
        migrations.AlterField(
            model_name='activeorder',
            name='type',
            field=models.CharField(choices=[('LIMIT', 'Limit'), ('MARKET', 'Market'), ('MOC', 'MarketonClose'), ('LOC', 'LimitOnClose'), ('STOP', 'Stop'), ('STOPLIMIT', 'STOPLIMIT')], max_length=9),
        ),
    ]
