# Generated by Django 4.1.7 on 2023-07-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_activeorder_activation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorder',
            name='tif',
            field=models.CharField(choices=[('Day', 'Day'), ('GTC', 'GoodTilCanceled')], max_length=3),
        ),
    ]
