# Generated by Django 4.2.4 on 2023-08-13 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_activeorder_tif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorder',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 0, 0)),
        ),
        migrations.AlterField(
            model_name='activeorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 0, 0)),
        ),
    ]
